const MAP_MOVE = 'MAP_MOVE';
const MAP_CLICK_FEATURE = 'MAP_CLICK_FEATURE';
const MAP_CLOSE_POPUP = 'MAP_CLOSE_POPUP';
const MAP_ZOOM_UPDATE = 'MAP_ZOOM_UPDATE';

module.exports = {
  MAP_MOVE,
  MAP_CLICK_FEATURE,
  MAP_CLOSE_POPUP,
  MAP_ZOOM_UPDATE,
};
